@echo off
set BASE_PATH=F:\Knowledge Extraction_v2\Output_true3

python metrics2.py --function_output_path "%BASE_PATH%\output_LLAMA70B\output_path_function_baai.csv" --function_txt_path "%BASE_PATH%\output_LLAMA70B\output_path_function_baai_0.5.txt" --theme_output_path "%BASE_PATH%\output_LLAMA70B\output_path_theme_baai.csv" --theme_txt_path "%BASE_PATH%\output_LLAMA70B\output_path_theme_baai_0.5.txt"
python metrics2.py --function_output_path "%BASE_PATH%\output_LLAMA70B\output_path_function_sentence-t5-large.csv" --function_txt_path "%BASE_PATH%\output_LLAMA70B\output_path_function_sentence-t5-large_0.5.txt" --theme_output_path "%BASE_PATH%\output_LLAMA70B\output_path_theme_sentence-t5-large.csv" --theme_txt_path "%BASE_PATH%\output_LLAMA70B\output_path_theme_sentence-t5-large_0.5.txt"
python metrics2.py --function_output_path "%BASE_PATH%\output_LLAMA70B\output_path_function_llama70b.csv" --function_txt_path "%BASE_PATH%\output_LLAMA70B\output_path_function_llama70b_0.5.txt" --theme_output_path "%BASE_PATH%\output_LLAMA70B\output_path_theme_llama70b.csv" --theme_txt_path "%BASE_PATH%\output_LLAMA70B\output_path_theme_llama70b_0.5.txt"

python metrics2.py --function_output_path "%BASE_PATH%\output_GPT3.5\output_path_function_baai.csv" --function_txt_path "%BASE_PATH%\output_GPT3.5\output_path_function_baai_0.5.txt" --theme_output_path "%BASE_PATH%\output_GPT3.5\output_path_theme_baai.csv" --theme_txt_path "%BASE_PATH%\output_GPT3.5\output_path_theme_baai_0.5.txt"
python metrics2.py --function_output_path "%BASE_PATH%\output_GPT3.5\output_path_function_sentence-t5-large.csv" --function_txt_path "%BASE_PATH%\output_GPT3.5\output_path_function_sentence-t5-large_0.5.txt" --theme_output_path "%BASE_PATH%\output_GPT3.5\output_path_theme_sentence-t5-large.csv" --theme_txt_path "%BASE_PATH%\output_GPT3.5\output_path_theme_sentence-t5-large_0.5.txt"
python metrics2.py --function_output_path "%BASE_PATH%\output_GPT3.5\output_path_function_gpt3.5.csv" --function_txt_path "%BASE_PATH%\output_GPT3.5\output_path_function_gpt3.5_0.5.txt" --theme_output_path "%BASE_PATH%\output_GPT3.5\output_path_theme_gpt3.5.csv" --theme_txt_path "%BASE_PATH%\output_GPT3.5\output_path_theme_gpt3.5_0.5.txt"

python metrics2.py --function_output_path "%BASE_PATH%\output_GPT4o\output_path_function_baai.csv" --function_txt_path "%BASE_PATH%\output_GPT4o\output_path_function_baai_0.5.txt" --theme_output_path "%BASE_PATH%\output_GPT4o\output_path_theme_baai.csv" --theme_txt_path "%BASE_PATH%\output_GPT4o\output_path_theme_baai_0.5.txt"
python metrics2.py --function_output_path "%BASE_PATH%\output_GPT4o\output_path_function_sentence-t5-large.csv" --function_txt_path "%BASE_PATH%\output_GPT4o\output_path_function_sentence-t5-large_0.5.txt" --theme_output_path "%BASE_PATH%\output_GPT4o\output_path_theme_sentence-t5-large.csv" --theme_txt_path "%BASE_PATH%\output_GPT4o\output_path_theme_sentence-t5-large_0.5.txt"
python metrics2.py --function_output_path "%BASE_PATH%\output_GPT4o\output_path_function_gpt4o.csv" --function_txt_path "%BASE_PATH%\output_GPT4o\output_path_function_gpt4o_0.5.txt" --theme_output_path "%BASE_PATH%\output_GPT4o\output_path_theme_gpt4o.csv" --theme_txt_path "%BASE_PATH%\output_GPT4o\output_path_theme_gpt4o_0.5.txt"

@REM python metrics2.py --function_output_path "%BASE_PATH%\output_LLAMA70B_RE\output_path_function_baai.csv" --function_txt_path "%BASE_PATH%\output_LLAMA70B_RE\output_path_function_baai_0.5.txt" --theme_output_path "%BASE_PATH%\output_LLAMA70B_RE\output_path_theme_baai.csv" --theme_txt_path "%BASE_PATH%\output_LLAMA70B_RE\output_path_theme_baai_0.5.txt"
@REM python metrics2.py --function_output_path "%BASE_PATH%\output_LLAMA70B_RE\output_path_function_sentence-t5-large.csv" --function_txt_path "%BASE_PATH%\output_LLAMA70B_RE\output_path_function_sentence-t5-large_0.5.txt" --theme_output_path "%BASE_PATH%\output_LLAMA70B_RE\output_path_theme_sentence-t5-large.csv" --theme_txt_path "%BASE_PATH%\output_LLAMA70B_RE\output_path_theme_sentence-t5-large_0.5.txt"
@REM
@REM python metrics2.py --function_output_path "%BASE_PATH%\output_LLAMA70B_Schema_NoE\output_path_function_baai.csv" --function_txt_path "%BASE_PATH%\output_LLAMA70B_Schema_NoE\output_path_function_baai_0.5.txt" --theme_output_path "%BASE_PATH%\output_LLAMA70B_Schema_NoE\output_path_theme_baai.csv" --theme_txt_path "%BASE_PATH%\output_LLAMA70B_Schema_NoE\output_path_theme_baai_0.5.txt"
@REM python metrics2.py --function_output_path "%BASE_PATH%\output_LLAMA70B_Schema_NoE\output_path_function_sentence-t5-large.csv" --function_txt_path "%BASE_PATH%\output_LLAMA70B_Schema_NoE\output_path_function_sentence-t5-large_0.5.txt" --theme_output_path "%BASE_PATH%\output_LLAMA70B_Schema_NoE\output_path_theme_sentence-t5-large.csv" --theme_txt_path "%BASE_PATH%\output_LLAMA70B_Schema_NoE\output_path_theme_sentence-t5-large_0.5.txt"
@REM
@REM python metrics2.py --function_output_path "%BASE_PATH%\output_LLAMA70B_Schema_NoR\output_path_function_baai.csv" --function_txt_path "%BASE_PATH%\output_LLAMA70B_Schema_NoR\output_path_function_baai_0.5.txt" --theme_output_path "%BASE_PATH%\output_LLAMA70B_Schema_NoR\output_path_theme_baai.csv" --theme_txt_path "%BASE_PATH%\output_LLAMA70B_Schema_NoR\output_path_theme_baai_0.5.txt"
@REM python metrics2.py --function_output_path "%BASE_PATH%\output_LLAMA70B_Schema_NoR\output_path_function_sentence-t5-large.csv" --function_txt_path "%BASE_PATH%\output_LLAMA70B_Schema_NoR\output_path_function_sentence-t5-large_0.5.txt" --theme_output_path "%BASE_PATH%\output_LLAMA70B_Schema_NoR\output_path_theme_sentence-t5-large.csv" --theme_txt_path "%BASE_PATH%\output_LLAMA70B_Schema_NoR\output_path_theme_sentence-t5-large_0.5.txt"

