@echo off
set BASE_PATH=.

python metrics2.py --relation_truth_path "%BASE_PATH%\Data\GPT4.0\relation_with_function_true.csv" --relation_result_path "%BASE_PATH%\Data\LLAMA70B\relation_with_function_baai.csv" --concept_path "%BASE_PATH%\Output\output_LLAMA70B\output_path_function_baai.csv" --relation_txt_path "%BASE_PATH%\Output\output_LLAMA70B\output_relation_baai_1.0.txt"
python metrics2.py --relation_truth_path "%BASE_PATH%\Data\GPT4.0\relation_with_function_true.csv" --relation_result_path "%BASE_PATH%\Data\LLAMA70B\relation_with_function_sentence-t5-large.csv" --concept_path "%BASE_PATH%\Output\output_LLAMA70B\output_path_function_sentence-t5-large.csv" --relation_txt_path "%BASE_PATH%\Output\output_LLAMA70B\output_relation_sentence-t5-large_1.0.txt"
python metrics2.py --relation_truth_path "%BASE_PATH%\Data\GPT4.0\relation_with_function_true.csv" --relation_result_path "%BASE_PATH%\Data\LLAMA70B\relation_with_function_llama70b.csv" --concept_path "%BASE_PATH%\Output\output_LLAMA70B\output_path_function_llama70b.csv" --relation_txt_path "%BASE_PATH%\Output\output_LLAMA70B\output_relation_llama70b_1.0.txt"

python metrics2.py --relation_truth_path "%BASE_PATH%\Data\GPT4.0\relation_with_function_true.csv" --relation_result_path "%BASE_PATH%\Data\GPT3.5\relation_with_function_baai.csv" --concept_path "%BASE_PATH%\Output\output_GPT3.5\output_path_function_baai.csv" --relation_txt_path "%BASE_PATH%\Output\output_GPT3.5\output_relation_baai_1.0.txt"
python metrics2.py --relation_truth_path "%BASE_PATH%\Data\GPT4.0\relation_with_function_true.csv" --relation_result_path "%BASE_PATH%\Data\GPT3.5\relation_with_function_sentence-t5-large.csv" --concept_path "%BASE_PATH%\Output\output_GPT3.5\output_path_function_sentence-t5-large.csv" --relation_txt_path "%BASE_PATH%\Output\output_GPT3.5\output_relation_sentence-t5-large_1.0.txt"
python metrics2.py --relation_truth_path "%BASE_PATH%\Data\GPT4.0\relation_with_function_true.csv" --relation_result_path "%BASE_PATH%\Data\GPT3.5\relation_with_function_gpt3.5.csv" --concept_path "%BASE_PATH%\Output\output_GPT3.5\output_path_function_gpt3.5.csv" --relation_txt_path "%BASE_PATH%\Output\output_GPT3.5\output_relation_gpt3.5_1.0.txt"

python metrics2.py --relation_truth_path "%BASE_PATH%\Data\GPT4.0\relation_with_function_true.csv" --relation_result_path "%BASE_PATH%\Data\GPT4o\relation_with_function_baai.csv" --concept_path "%BASE_PATH%\Output\output_GPT4o\output_path_function_baai.csv" --relation_txt_path "%BASE_PATH%\Output\output_GPT4o\output_relation_baai_1.0.txt"
python metrics2.py --relation_truth_path "%BASE_PATH%\Data\GPT4.0\relation_with_function_true.csv" --relation_result_path "%BASE_PATH%\Data\GPT4o\relation_with_function_sentence-t5-large.csv" --concept_path "%BASE_PATH%\Output\output_GPT4o\output_path_function_sentence-t5-large.csv" --relation_txt_path "%BASE_PATH%\Output\output_GPT4o\output_relation_sentence-t5-large_1.0.txt"
python metrics2.py --relation_truth_path "%BASE_PATH%\Data\GPT4.0\relation_with_function_true.csv" --relation_result_path "%BASE_PATH%\Data\GPT4o\relation_with_function_gpt4o.csv" --concept_path "%BASE_PATH%\Output\output_GPT4o\output_path_function_gpt4o.csv" --relation_txt_path "%BASE_PATH%\Output\output_GPT4o\output_relation_gpt4o_1.0.txt"

python metrics2.py --relation_truth_path "%BASE_PATH%\Data\GPT4.0\relation_with_function_true.csv" --relation_result_path "%BASE_PATH%\Data\LLAMA70B_RE\relation_with_function_baai.csv" --concept_path "%BASE_PATH%\Output\output_LLAMA70B_RE\output_path_function_baai.csv" --relation_txt_path "%BASE_PATH%\Output\output_LLAMA70B_RE\output_relation_baai_1.0.txt"
python metrics2.py --relation_truth_path "%BASE_PATH%\Data\GPT4.0\relation_with_function_true.csv" --relation_result_path "%BASE_PATH%\Data\LLAMA70B_RE\relation_with_function_sentence-t5-large.csv" --concept_path "%BASE_PATH%\Output\output_LLAMA70B_RE\output_path_function_sentence-t5-large.csv" --relation_txt_path "%BASE_PATH%\Output\output_LLAMA70B_RE\output_relation_sentence-t5-large_1.0.txt"

python metrics2.py --relation_truth_path "%BASE_PATH%\Data\GPT4.0\relation_with_function_true.csv" --relation_result_path "%BASE_PATH%\Data\LLAMA70B_Schema_NoE\relation_with_function_baai.csv" --concept_path "%BASE_PATH%\Output\output_LLAMA70B_Schema_NoE\output_path_function_baai.csv" --relation_txt_path "%BASE_PATH%\Output\output_LLAMA70B_Schema_NoE\output_relation_baai_1.0.txt"
python metrics2.py --relation_truth_path "%BASE_PATH%\Data\GPT4.0\relation_with_function_true.csv" --relation_result_path "%BASE_PATH%\Data\LLAMA70B_Schema_NoE\relation_with_function_sentence-t5-large.csv" --concept_path "%BASE_PATH%\Output\output_LLAMA70B_Schema_NoE\output_path_function_sentence-t5-large.csv" --relation_txt_path "%BASE_PATH%\Output\output_LLAMA70B_Schema_NoE\output_relation_sentence-t5-large_1.0.txt"

python metrics2.py --relation_truth_path "%BASE_PATH%\Data\GPT4.0\relation_with_function_true.csv" --relation_result_path "%BASE_PATH%\Data\LLAMA70B_Schema_NoR\relation_with_function_baai.csv" --concept_path "%BASE_PATH%\Output\output_LLAMA70B_Schema_NoR\output_path_function_baai.csv" --relation_txt_path "%BASE_PATH%\Output\output_LLAMA70B_Schema_NoR\output_relation_baai_1.0.txt"
python metrics2.py --relation_truth_path "%BASE_PATH%\Data\GPT4.0\relation_with_function_true.csv" --relation_result_path "%BASE_PATH%\Data\LLAMA70B_Schema_NoR\relation_with_function_sentence-t5-large.csv" --concept_path "%BASE_PATH%\Output\output_LLAMA70B_Schema_NoR\output_path_function_sentence-t5-large.csv" --relation_txt_path "%BASE_PATH%\Output\output_LLAMA70B_Schema_NoR\output_relation_sentence-t5-large_1.0.txt"
