@echo off

@REM python func_theme_update.py --model "sentence-transformers/sentence-t5-large" --input "F:\Knowledge Extraction_v2\Data\LLAMA70B2\function_sample.csv" --output "F:\Knowledge Extraction_v2\Data\LLAMA70B2\function_sample.csv" --embeddings "F:\Knowledge Extraction_v2\03 SLM_Standerlization\function_sentence-t5-large.pth"
@REM python func_theme_update.py --model "BAAI/bge-m3" --input "F:\Knowledge Extraction_v2\Data\LLAMA70B2\function_sample.csv" --output "F:\Knowledge Extraction_v2\Data\LLAMA70B2\function_sample.csv" --embeddings "F:\Knowledge Extraction_v2\03 SLM_Standerlization\function_baai.pth"
@REM python func_theme_update.py --model "sentence-transformers/sentence-t5-large" --input "F:\Knowledge Extraction_v2\Data\LLAMA70B2\theme_sample.csv" --output "F:\Knowledge Extraction_v2\Data\LLAMA70B2\theme_sample.csv" --embeddings "F:\Knowledge Extraction_v2\03 SLM_Standerlization\theme_sentence-t5-large.pth"
@REM python func_theme_update.py --model "BAAI/bge-m3" --input "F:\Knowledge Extraction_v2\Data\LLAMA70B2\theme_sample.csv" --output "F:\Knowledge Extraction_v2\Data\LLAMA70B2\theme_sample.csv" --embeddings "F:\Knowledge Extraction_v2\03 SLM_Standerlization\theme_baai.pth"
@REM
@REM python func_theme_update.py --model "sentence-transformers/sentence-t5-large" --input "F:\Knowledge Extraction_v2\Data\LLAMA70B_RE\function_sample.csv" --output "F:\Knowledge Extraction_v2\Data\LLAMA70B_RE\function_sample.csv" --embeddings "F:\Knowledge Extraction_v2\03 SLM_Standerlization\function_sentence-t5-large.pth"
@REM python func_theme_update.py --model "BAAI/bge-m3" --input "F:\Knowledge Extraction_v2\Data\LLAMA70B_RE\function_sample.csv" --output "F:\Knowledge Extraction_v2\Data\LLAMA70B_RE\function_sample.csv" --embeddings "F:\Knowledge Extraction_v2\03 SLM_Standerlization\function_baai.pth"
@REM python func_theme_update.py --model "sentence-transformers/sentence-t5-large" --input "F:\Knowledge Extraction_v2\Data\LLAMA70B_RE\theme_sample.csv" --output "F:\Knowledge Extraction_v2\Data\LLAMA70B_RE\theme_sample.csv" --embeddings "F:\Knowledge Extraction_v2\03 SLM_Standerlization\theme_sentence-t5-large.pth"
@REM python func_theme_update.py --model "BAAI/bge-m3" --input "F:\Knowledge Extraction_v2\Data\LLAMA70B_RE\theme_sample.csv" --output "F:\Knowledge Extraction_v2\Data\LLAMA70B_RE\theme_sample.csv" --embeddings "F:\Knowledge Extraction_v2\03 SLM_Standerlization\theme_baai.pth"
@REM
@REM python func_theme_update.py --model "sentence-transformers/sentence-t5-large" --input "F:\Knowledge Extraction_v2\Data\LLAMA70B_Schema_NoE\function_sample.csv" --output "F:\Knowledge Extraction_v2\Data\LLAMA70B_Schema_NoE\function_sample.csv" --embeddings "F:\Knowledge Extraction_v2\03 SLM_Standerlization\function_sentence-t5-large.pth"
@REM python func_theme_update.py --model "BAAI/bge-m3" --input "F:\Knowledge Extraction_v2\Data\LLAMA70B_Schema_NoE\function_sample.csv" --output "F:\Knowledge Extraction_v2\Data\LLAMA70B_Schema_NoE\function_sample.csv" --embeddings "F:\Knowledge Extraction_v2\03 SLM_Standerlization\function_baai.pth"
@REM python func_theme_update.py --model "sentence-transformers/sentence-t5-large" --input "F:\Knowledge Extraction_v2\Data\LLAMA70B_Schema_NoE\theme_sample.csv" --output "F:\Knowledge Extraction_v2\Data\LLAMA70B_Schema_NoE\theme_sample.csv" --embeddings "F:\Knowledge Extraction_v2\03 SLM_Standerlization\theme_sentence-t5-large.pth"
@REM python func_theme_update.py --model "BAAI/bge-m3" --input "F:\Knowledge Extraction_v2\Data\LLAMA70B_Schema_NoE\theme_sample.csv" --output "F:\Knowledge Extraction_v2\Data\LLAMA70B_Schema_NoE\theme_sample.csv" --embeddings "F:\Knowledge Extraction_v2\03 SLM_Standerlization\theme_baai.pth"
@REM
@REM python func_theme_update.py --model "sentence-transformers/sentence-t5-large" --input "F:\Knowledge Extraction_v2\Data\LLAMA70B_Schema_NoR\function_sample.csv" --output "F:\Knowledge Extraction_v2\Data\LLAMA70B_Schema_NoR\function_sample.csv" --embeddings "F:\Knowledge Extraction_v2\03 SLM_Standerlization\function_sentence-t5-large.pth"
@REM python func_theme_update.py --model "BAAI/bge-m3" --input "F:\Knowledge Extraction_v2\Data\LLAMA70B_Schema_NoR\function_sample.csv" --output "F:\Knowledge Extraction_v2\Data\LLAMA70B_Schema_NoR\function_sample.csv" --embeddings "F:\Knowledge Extraction_v2\03 SLM_Standerlization\function_baai.pth"
@REM python func_theme_update.py --model "sentence-transformers/sentence-t5-large" --input "F:\Knowledge Extraction_v2\Data\LLAMA70B_Schema_NoR\theme_sample.csv" --output "F:\Knowledge Extraction_v2\Data\LLAMA70B_Schema_NoR\theme_sample.csv" --embeddings "F:\Knowledge Extraction_v2\03 SLM_Standerlization\theme_sentence-t5-large.pth"
@REM python func_theme_update.py --model "BAAI/bge-m3" --input "F:\Knowledge Extraction_v2\Data\LLAMA70B_Schema_NoR\theme_sample.csv" --output "F:\Knowledge Extraction_v2\Data\LLAMA70B_Schema_NoR\theme_sample.csv" --embeddings "F:\Knowledge Extraction_v2\03 SLM_Standerlization\theme_baai.pth"

@REM python func_theme_update.py --model "sentence-transformers/sentence-t5-large" --input "F:\Knowledge Extraction_v2\Data\GPT4o\function_sample.csv" --output "F:\Knowledge Extraction_v2\Data\GPT4o\function_sample.csv" --embeddings "F:\Knowledge Extraction_v2\03 SLM_Standerlization\function_sentence-t5-large.pth"
@REM python func_theme_update.py --model "BAAI/bge-m3" --input "F:\Knowledge Extraction_v2\Data\GPT4o\function_sample.csv" --output "F:\Knowledge Extraction_v2\Data\GPT4o\function_sample.csv" --embeddings "F:\Knowledge Extraction_v2\03 SLM_Standerlization\function_baai.pth"
@REM python func_theme_update.py --model "sentence-transformers/sentence-t5-large" --input "F:\Knowledge Extraction_v2\Data\GPT4o\theme_sample.csv" --output "F:\Knowledge Extraction_v2\Data\GPT4o\theme_sample.csv" --embeddings "F:\Knowledge Extraction_v2\03 SLM_Standerlization\theme_sentence-t5-large.pth"
@REM python func_theme_update.py --model "BAAI/bge-m3" --input "F:\Knowledge Extraction_v2\Data\GPT4o\theme_sample.csv" --output "F:\Knowledge Extraction_v2\Data\GPT4o\theme_sample.csv" --embeddings "F:\Knowledge Extraction_v2\03 SLM_Standerlization\theme_baai.pth"

@REM python func_theme_update.py --model "sentence-transformers/sentence-t5-large" --input "F:\Knowledge Extraction_v2\Data\GPT4o\function_sample.csv" --output "F:\Knowledge Extraction_v2\Data\GPT4o\function_sample.csv" --embeddings "F:\Knowledge Extraction_v2\03 SLM_Standerlization\function_sentence-t5-large.pth"
@REM python func_theme_update.py --model "BAAI/bge-m3" --input "F:\Knowledge Extraction_v2\Data\GPT4o\function_sample.csv" --output "F:\Knowledge Extraction_v2\Data\GPT4o\function_sample.csv" --embeddings "F:\Knowledge Extraction_v2\03 SLM_Standerlization\function_baai.pth"
@REM python func_theme_update.py --model "sentence-transformers/sentence-t5-large" --input "F:\Knowledge Extraction_v2\Data\GPT4o\theme_sample.csv" --output "F:\Knowledge Extraction_v2\Data\GPT4o\theme_sample.csv" --embeddings "F:\Knowledge Extraction_v2\03 SLM_Standerlization\theme_sentence-t5-large.pth"
@REM python func_theme_update.py --model "BAAI/bge-m3" --input "F:\Knowledge Extraction_v2\Data\GPT4o\theme_sample.csv" --output "F:\Knowledge Extraction_v2\Data\GPT4o\theme_sample.csv" --embeddings "F:\Knowledge Extraction_v2\03 SLM_Standerlization\theme_baai.pth"

@REM python func_theme_update.py --model "sentence-transformers/sentence-t5-large" --input "F:\Knowledge Extraction_v2\Data\GPT3.5\function_sample.csv" --output "F:\Knowledge Extraction_v2\Data\GPT3.5\function_sample.csv" --embeddings "F:\Knowledge Extraction_v2\03 SLM_Standerlization\function_sentence-t5-large.pth"
@REM python func_theme_update.py --model "BAAI/bge-m3" --input "F:\Knowledge Extraction_v2\Data\GPT3.5\function_sample.csv" --output "F:\Knowledge Extraction_v2\Data\GPT3.5\function_sample.csv" --embeddings "F:\Knowledge Extraction_v2\03 SLM_Standerlization\function_baai.pth"
python func_theme_update.py --model "sentence-transformers/sentence-t5-large" --input "F:\Knowledge Extraction_v2\Data\GPT3.5\theme_sample.csv" --output "F:\Knowledge Extraction_v2\Data\GPT3.5\theme_sample.csv" --embeddings "F:\Knowledge Extraction_v2\03 SLM_Standerlization\theme_sentence-t5-large.pth"
python func_theme_update.py --model "BAAI/bge-m3" --input "F:\Knowledge Extraction_v2\Data\GPT3.5\theme_sample.csv" --output "F:\Knowledge Extraction_v2\Data\GPT3.5\theme_sample.csv" --embeddings "F:\Knowledge Extraction_v2\03 SLM_Standerlization\theme_baai.pth"